-   id: clang-format-docker
    name: clang-format (via docker)
    description: clang-format, but provided by docker
    entry: clang-format -i
    language: docker
    files: \.cpp$ \.cc$ \.c$ \.h$ \.hh$ \.hpp$
